spring:
  datasource:
   
   url: jdbc:mysql://127.0.0.1:3306/shoppingmall?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
   username: root
   password: 852025
   driver-class-name: com.mysql.cj.jdbc.Driver
   initialization-mode: always
pagehelper:  helper-dialect: mysql
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
  params: count=countSqllogging:  level:    com.example.dao: DEBUG
    